name: Deploy Application

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set variables
        if: github.event.workflow_run.conclusion == 'success'
        run: |
          echo "BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          echo "SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV


      - name: Print deployment info
        if: github.event.workflow_run.conclusion == 'success'
        run: |
          echo "Ready to deploy"
          echo "Branch: $BRANCH"
          echo "Image tag: $BRANCH-$SHA"


      - name: Print failure message
        if: github.event.workflow_run.conclusion != 'success'
        run: |
          echo "Build failed. Deployment skipped."