name: Build Docker Images

permissions:
  contents: read
  packages: write
  
on:
  push:
    branches:
      - dev
      - stage
      - uat
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "REPO_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build API Image
        run: |
          docker build \
          -t ghcr.io/${REPO_LC}/productmanagement-api:${BRANCH}-${SHA} \
          -f Backend/ProductManagement.API/Dockerfile \
          Backend

      - name: Build Frontend Image
        run: |
          docker build \
          -t ghcr.io/${REPO_LC}/productmanagement-frontend:${BRANCH}-${SHA} \
          ./Frontend

      - name: Push API Image
        run: |
          docker push ghcr.io/${REPO_LC}/productmanagement-api:${BRANCH}-${SHA}

      - name: Push Frontend Image
        run: |
          docker push ghcr.io/${REPO_LC}/productmanagement-frontend:${BRANCH}-${SHA}